2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Current SDK version is 0.17.9
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Configure stats pid to 85950
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Loading settings from /home/daniel/.config/wandb/settings
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Loading settings from /home/daniel/dev/kan-pref/pref_kan/notebooks/wandb/settings
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Applying login settings: {'api_key': '***REDACTED***'}
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_init.py:_log_setup():524] Logging user logs to /home/daniel/dev/kan-pref/pref_kan/notebooks/wandb/run-20240926_002852-f634qyvc/logs/debug.log
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_init.py:_log_setup():525] Logging internal logs to /home/daniel/dev/kan-pref/pref_kan/notebooks/wandb/run-20240926_002852-f634qyvc/logs/debug-internal.log
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_init.py:init():608] calling init triggers
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_init.py:init():615] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_init.py:init():658] starting backend
2024-09-26 00:28:52,005 INFO    MainThread:85950 [wandb_init.py:init():662] setting up manager
2024-09-26 00:28:52,006 INFO    MainThread:85950 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-26 00:28:52,006 INFO    MainThread:85950 [wandb_init.py:init():670] backend started and connected
2024-09-26 00:28:52,008 INFO    MainThread:85950 [wandb_run.py:_label_probe_notebook():1344] probe notebook
2024-09-26 00:28:52,008 INFO    MainThread:85950 [wandb_run.py:_label_probe_notebook():1354] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-26 00:28:52,008 INFO    MainThread:85950 [wandb_init.py:init():768] updated telemetry
2024-09-26 00:28:52,016 INFO    MainThread:85950 [wandb_init.py:init():801] communicating run to backend with 90.0 second timeout
2024-09-26 00:28:52,287 ERROR   MainThread:85950 [wandb_init.py:init():827] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-26 00:28:52,287 ERROR   MainThread:85950 [wandb_init.py:init():1239] error in wandb.init()
Traceback (most recent call last):
  File "/home/daniel/software/anaconda3/envs/kan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1229, in init
    return wi.init()
  File "/home/daniel/software/anaconda3/envs/kan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 833, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-26 00:28:57,536 INFO    MainThread:85950 [wandb_settings.py:_apply_login():1970] Applying login settings: {}
2024-09-26 00:28:57,539 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Current SDK version is 0.17.9
2024-09-26 00:28:57,539 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Configure stats pid to 85950
2024-09-26 00:28:57,539 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Loading settings from /home/daniel/.config/wandb/settings
2024-09-26 00:28:57,539 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Loading settings from /home/daniel/dev/kan-pref/pref_kan/notebooks/wandb/settings
2024-09-26 00:28:57,539 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-09-26 00:28:57,539 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-26 00:28:57,539 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-26 00:28:57,539 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-26 00:28:57,540 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Applying login settings: {'api_key': '***REDACTED***'}
2024-09-26 00:28:57,540 INFO    MainThread:85950 [wandb_init.py:_log_setup():524] Logging user logs to /home/daniel/dev/kan-pref/pref_kan/notebooks/wandb/run-20240926_002857-ur7iftka/logs/debug.log
2024-09-26 00:28:57,540 INFO    MainThread:85950 [wandb_init.py:_log_setup():525] Logging internal logs to /home/daniel/dev/kan-pref/pref_kan/notebooks/wandb/run-20240926_002857-ur7iftka/logs/debug-internal.log
2024-09-26 00:28:57,540 INFO    MainThread:85950 [wandb_init.py:init():608] calling init triggers
2024-09-26 00:28:57,540 INFO    MainThread:85950 [wandb_init.py:init():615] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2024-09-26 00:28:57,540 INFO    MainThread:85950 [wandb_init.py:init():658] starting backend
2024-09-26 00:28:57,540 INFO    MainThread:85950 [wandb_init.py:init():662] setting up manager
2024-09-26 00:28:57,541 INFO    MainThread:85950 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-26 00:28:57,541 INFO    MainThread:85950 [wandb_init.py:init():670] backend started and connected
2024-09-26 00:28:57,543 INFO    MainThread:85950 [wandb_run.py:_label_probe_notebook():1344] probe notebook
2024-09-26 00:28:57,543 INFO    MainThread:85950 [wandb_run.py:_label_probe_notebook():1354] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-26 00:28:57,543 INFO    MainThread:85950 [wandb_init.py:init():768] updated telemetry
2024-09-26 00:28:57,552 INFO    MainThread:85950 [wandb_init.py:init():801] communicating run to backend with 90.0 second timeout
2024-09-26 00:28:57,825 ERROR   MainThread:85950 [wandb_init.py:init():827] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-26 00:28:57,825 ERROR   MainThread:85950 [wandb_init.py:init():1239] error in wandb.init()
Traceback (most recent call last):
  File "/home/daniel/software/anaconda3/envs/kan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1229, in init
    return wi.init()
  File "/home/daniel/software/anaconda3/envs/kan/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 833, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-26 00:29:28,301 INFO    MainThread:85950 [wandb_settings.py:_apply_login():1970] Applying login settings: {}
2024-09-26 00:29:28,307 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Current SDK version is 0.17.9
2024-09-26 00:29:28,307 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Configure stats pid to 85950
2024-09-26 00:29:28,307 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Loading settings from /home/daniel/.config/wandb/settings
2024-09-26 00:29:28,307 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Loading settings from /home/daniel/dev/kan-pref/pref_kan/notebooks/wandb/settings
2024-09-26 00:29:28,307 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-09-26 00:29:28,307 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-26 00:29:28,307 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-09-26 00:29:28,308 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-26 00:29:28,308 INFO    MainThread:85950 [wandb_setup.py:_flush():77] Applying login settings: {'api_key': '***REDACTED***'}
2024-09-26 00:29:28,308 INFO    MainThread:85950 [wandb_init.py:_log_setup():524] Logging user logs to /home/daniel/dev/kan-pref/pref_kan/notebooks/wandb/run-20240926_002928-5qm1w0yu/logs/debug.log
2024-09-26 00:29:28,308 INFO    MainThread:85950 [wandb_init.py:_log_setup():525] Logging internal logs to /home/daniel/dev/kan-pref/pref_kan/notebooks/wandb/run-20240926_002928-5qm1w0yu/logs/debug-internal.log
2024-09-26 00:29:28,308 INFO    MainThread:85950 [wandb_init.py:init():608] calling init triggers
2024-09-26 00:29:28,308 INFO    MainThread:85950 [wandb_init.py:init():615] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'entity': 'dlsmarta', 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2024-09-26 00:29:28,308 INFO    MainThread:85950 [wandb_init.py:init():658] starting backend
2024-09-26 00:29:28,308 INFO    MainThread:85950 [wandb_init.py:init():662] setting up manager
2024-09-26 00:29:28,310 INFO    MainThread:85950 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-26 00:29:28,311 INFO    MainThread:85950 [wandb_init.py:init():670] backend started and connected
2024-09-26 00:29:28,314 INFO    MainThread:85950 [wandb_run.py:_label_probe_notebook():1344] probe notebook
2024-09-26 00:29:28,314 INFO    MainThread:85950 [wandb_run.py:_label_probe_notebook():1354] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-09-26 00:29:28,314 INFO    MainThread:85950 [wandb_init.py:init():768] updated telemetry
2024-09-26 00:29:28,323 INFO    MainThread:85950 [wandb_init.py:init():801] communicating run to backend with 90.0 second timeout
